---
- name: Update packages
  ansible.builtin.apt:
    cache_valid_time: 86400
    update_cache: yes

- name: Install OTel tasks
  ansible.builtin.import_tasks: otel.yml
  tags: otel

- name: Install Prometheus tasks
  ansible.builtin.import_tasks: prometheus.yml
  tags: prometheus