---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - ufw

- name: Download Open Telemetry Collector
  ansible.builtin.get_url:
    url: 'https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.61.0/otelcol_0.61.0_linux_amd64.deb'
    dest:  /tmp/otelcol_linux_amd64.deb
    mode: 0644

- name: Install Open Telemetry Collector
  ansible.builtin.apt:
    deb: /tmp/otelcol_linux_amd64.deb

- name: Copy Open Telemetry config
  ansible.builtin.copy:
     src: files/config.yaml
     dest: /etc/otelcol
     mode: 0644
  notify: Restart Open Telemetry Collector