---
- name: Create Prometheus system group
  ansible.builtin.group:
    name: prometheus
    state: present
    system: true

- name: Create Prometheus system user
  ansible.builtin.user:
    name: prometheus
    group: prometheus
    shell: /sbin/nologin
    system: true

- name: Create data directory
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
    mode: 0755
    owner: prometheus
    group: prometheus

- name: Create config directories
  ansible.builtin.file:
    path: '/etc/prometheus/{{ item }}'
    state: directory
    mode: 0755
    owner: prometheus
    group: prometheus
  with_items:
    - rules
    - rules.d
    - files_sd

- name: Download Prometheus
  ansible.builtin.unarchive:
    src: 'https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/{{ prometheus_directory }}.tar.gz'
    dest: /tmp
    remote_src: yes

- name: Copy executables
  ansible.builtin.copy:
    src: '/tmp/{{ prometheus_directory }}/{{ item }}'
    dest: /usr/local/bin
    mode: 0755
    remote_src: true
  with_items:
    - prometheus
    - promtool

- name: Copy config
  ansible.builtin.copy:
    src: '/tmp/{{ prometheus_directory }}/{{ item }}'
    dest: /etc/prometheus
    remote_src: true
    owner: prometheus
    group: prometheus
    mode: 0644
  with_items:
    - prometheus.yml
    - consoles
    - console_libraries


- name: Copy systemd service unit file
  ansible.builtin.copy:
     src: files/prometheus.service
     dest: /etc/systemd/system
     mode: 0644

- name: Start and enable Prometheus service
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: yes