---
# handlers file for ansible-otel
- name: Restart Open Telemetry Collector
  ansible.builtin.service:
    name: otelcol
    state: restarted

- name: Restart Prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted