---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-otel"
      ansible.builtin.include_role:
        name: "ansible-otel"
      tags:
        - always
    - name: Allow Prometheus UI in Molecule
      ansible.builtin.ufw:
        rule: allow
        port: 5000
        proto: tcp
      tags:
        - always
  vars:

