receivers:
  # Data sources: metrics
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      process:
      processes:

exporters:
  prometheus:
    endpoint: "localhost:9091"
    namespace: "default"

service:
  extensions: []
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: []
      exporters: [prometheus]